name: Bug report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed.
  - type: dropdown
    id: client
    attributes:
      label: What client do you play on?
      options:
      - enUS
      - enGB
      - deDE
      - esES
      - esMX
      - frFR
      - ruRU
      - other
    validations:
      required: true
  - type: dropdown
    id: faction
    attributes:
      label: Faction
      options:
      - Alliance
      - Horde
      - Both
    validations:
      required: true
  - type: dropdown
    id: phase
    attributes:
      label: "Content Phase:"
      options:
      - Generic
      - 1-19
      - 20-29
      - 30-39
      - 40-49
      - 50-59
      - '60'
      - 61-64
      - 65-69
      - '70'
      - 71-74
      - 75-79
      - '80'
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Describe the bug in detail. Database to link spells, NPCs, quests etc: https://wowgaming.altervista.org/aowow/
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Blizzlike Behaviour
      description: |
        Describe how it should be working without the bug. Link to evidence if possible such as YouTube videos or WoWHead comments from the time.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        HEADS UP: include sources in your bug report which are relevant to the 3.3.5a game version, 
        we will close any bug like "X should be changed to Y" reported without sources.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
        - Which commands to use? Which NPC to teleport to?
        - Do we need to have debug flags on Cmake?
        - Do we need to look at the console while the bug happens?
        - Other steps
        - Use the ingame commands to identify the unique GUID of an ore/herb/npc:    .npcinfo  /  .gobject near
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Any information that can help the developers to identify and fix the issue should be put here.
        Examples:
        Links to items/NPCs/quests from https://wowgaming.altervista.org/aowow/
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: os
    attributes:
      label: Operating system
      value: |
        Windows 11
    validations:
      required: true
  - type: textarea
    id: customizations
    attributes:
      label: Customizations
      value: |
        None
    validations:
      required: false
  - type: textarea
    id: server
    attributes:
      label: Realm in Iron Forges
      value: |
        Main
    validations:
      required: false
